const express = require("express");
const { pool, withTransaction } = require("../config/db");
const { requireAuth, requireWriteAccess } = require("../middleware/auth");
const { asyncHandler, paths, int, number, trim, finite, execute, first, rows, placeholders, jsonDecode, HttpError } = require("../lib/helpers");
const { findDuplicateTracking, buildShipmentNoteContext, refreshSplitNotesForTracking } = require("../lib/shipmentNotes");
const { getCargoPackageGroups, pendingPayrollGroupKeys, buildPayrollBreakdown, getDeliveredNotInCustoms } = require("../lib/cargo");

const router = express.Router(); router.use(requireAuth, requireWriteAccess);
const uid=(req)=>Number(req.user.user_id); const err=(res,status,message,key="success")=>res.status(status).json({[key]:false,error:message}); const ensureMonth=async(monthId,userId)=>Boolean(await first(pool,"SELECT id FROM month WHERE id=? AND user_id=? LIMIT 1",[monthId,userId]));
async function customReferencesBelong(db, userId, monthId, orderId, cartId) {
  if (orderId != null && !(await first(db, "SELECT id FROM orders WHERE id=? AND user_id=? AND month_id=? LIMIT 1", [orderId, userId, monthId]))) return false;
  if (cartId != null) {
    const cart = await first(db, "SELECT oc.id FROM order_carts oc JOIN orders o ON o.id=oc.order_id AND o.user_id=oc.user_id WHERE oc.id=? AND oc.user_id=? AND o.month_id=? AND (? IS NULL OR oc.order_id=?) LIMIT 1", [cartId, userId, monthId, orderId, orderId]);
    if (!cart) return false;
  }
  return true;
}

router.get(paths("getCustoms",true),asyncHandler(async(req,res)=>{const monthId=int(req.query.month_id);if(monthId<=0)return err(res,400,"month_id is required");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user");res.json(await rows(pool,`SELECT id,month_id,customs_fee,tracking_no,invoice_no,weight_kg,unit_price,delivery_fee,order_id,cart_id,order_ref,cart_ref,note,description FROM customs WHERE month_id=? AND user_id=? ORDER BY id DESC`,[monthId,uid(req)]));}));

router.post(paths("addCustom"),asyncHandler(async(req,res)=>{const d=req.body||{};let monthId=int(d.month_id);const fee=number(d.customs_fee);let tracking=Object.prototype.hasOwnProperty.call(d,"tracking_no")?trim(d.tracking_no):null;const invoice=Object.prototype.hasOwnProperty.call(d,"invoice_no")?trim(d.invoice_no):null;const weight=d.weight_kg==null||d.weight_kg===""?null:number(d.weight_kg);const unit=d.unit_price==null||d.unit_price===""?null:number(d.unit_price);const delivery=number(d.delivery_fee,0);let orderId=d.order_id==null?null:int(d.order_id),cartId=d.cart_id==null?null:int(d.cart_id),orderRef=d.order_ref==null?null:trim(d.order_ref),cartRef=d.cart_ref==null?null:trim(d.cart_ref),note=d.note==null?null:trim(d.note);let description=d.description==null?null:trim(d.description).toLowerCase();const source=d.source_message==null?null:String(d.source_message);if(!Object.prototype.hasOwnProperty.call(d,"customs_fee")||!finite(fee)||fee<0||(weight!==null&&(!finite(weight)||weight<0))||(unit!==null&&(!finite(unit)||unit<0))||!finite(delivery)||delivery<0)return err(res,400,"customs_fee, weight_kg, unit_price, and delivery_fee must be finite non-negative numbers");if(description==="")description=null;if(description!==null&&description.length>32)description=description.slice(0,32);if(monthId<=0)return err(res,400,"month_id is required");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user");let notifications=[];if(tracking){const duplicate=await findDuplicateTracking(pool,uid(req),tracking);if(duplicate)return res.status(409).json({success:false,error:"Tracking already exists in customs",duplicate:{id:Number(duplicate.id),month_id:Number(duplicate.month_id),tracking_no:duplicate.tracking_no||tracking}});const ctx=await buildShipmentNoteContext(pool,uid(req),monthId,tracking);notifications=ctx.notifications||[];if(Number(ctx.resolved_month_id)>0)monthId=Number(ctx.resolved_month_id);if(orderId==null&&ctx.order_id!=null)orderId=Number(ctx.order_id);if(cartId==null&&ctx.cart_id!=null)cartId=Number(ctx.cart_id);if(!orderRef&&ctx.order_ref)orderRef=ctx.order_ref;if(!cartRef&&ctx.cart_ref)cartRef=ctx.cart_ref;note=[note,...(ctx.note_parts||[])].map(trim).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(" | ")||note;}if(!(await ensureMonth(monthId,uid(req)))||!(await customReferencesBelong(pool,uid(req),monthId,orderId,cartId)))return err(res,422,"Referenced order/cart does not belong to this user and month");const result=await execute(pool,`INSERT INTO customs (month_id,customs_fee,user_id,tracking_no,invoice_no,weight_kg,unit_price,delivery_fee,order_id,cart_id,order_ref,cart_ref,note,description,source_message) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,[monthId,fee,uid(req),tracking||null,invoice||null,weight,unit,delivery,orderId,cartId,orderRef||null,cartRef||null,note||null,description,source]);res.json({success:true,id:Number(result.insertId),month_id:monthId,notifications});}));
router.post(paths("updateCustom"),asyncHandler(async(req,res)=>{const d=req.body||{};const id=int(d.id);const fee=number(d.customs_fee);const note=Object.prototype.hasOwnProperty.call(d,"note")?(d.note==null?null:trim(d.note)):null; if(!Object.prototype.hasOwnProperty.call(d,"customs_fee")||!finite(fee)||fee<0)return err(res,400,"customs_fee must be a finite non-negative number"); const hasTracking=Object.prototype.hasOwnProperty.call(d,"tracking_no");let tracking=hasTracking?trim(d.tracking_no):null;const hasWeight=Object.prototype.hasOwnProperty.call(d,"weight_kg");const weight=hasWeight?(d.weight_kg==null||d.weight_kg===""?null:number(d.weight_kg)):undefined;if(hasWeight&&weight!==null&&(!finite(weight)||weight<0))return err(res,400,"weight_kg must be a finite non-negative number");if(id<=0)return err(res,400,"id is required");if(tracking){const duplicate=await first(pool,"SELECT id,month_id,tracking_no FROM customs WHERE user_id=? AND id<>? AND tracking_no IS NOT NULL AND UPPER(TRIM(tracking_no))=UPPER(TRIM(?)) ORDER BY id DESC LIMIT 1",[uid(req),id,tracking]);if(duplicate)return res.status(409).json({success:false,error:"Tracking number already exists in customs",duplicate:{id:Number(duplicate.id),month_id:Number(duplicate.month_id),tracking_no:duplicate.tracking_no||""}});}const updates=["customs_fee=?","note=?"];const params=[fee,note];if(hasTracking){updates.push("tracking_no=?");params.push(tracking||null);}if(hasWeight){updates.push("weight_kg=?");params.push(weight);}params.push(id,uid(req));const result=await execute(pool,`UPDATE customs SET ${updates.join(",")} WHERE id=? AND user_id=?`,params);res.json({success:true,affected:result.affectedRows});}));
router.post(paths("deleteCustom"),asyncHandler(async(req,res)=>{const id=int(req.body?.id);if(id<=0)return err(res,400,"id is required");const item=await first(pool,"SELECT month_id,tracking_no FROM customs WHERE id=? AND user_id=? LIMIT 1",[id,uid(req)]);if(!item)return err(res,404,"Custom entry not found");const result=await execute(pool,"DELETE FROM customs WHERE id=? AND user_id=?",[id,uid(req)]);if(item.month_id&&item.tracking_no)await refreshSplitNotesForTracking(pool,uid(req),Number(item.month_id),item.tracking_no);res.json({success:true,affected:result.affectedRows});}));

function cleanNumber(value){if(value==null)return null;let s=String(value).trim().replace(/[\u00a0$]|USD|Kg/gi,"").replace(/[^0-9,.\-]/g,"");if(!s)return null;const comma=s.lastIndexOf(","),dot=s.lastIndexOf(".");if(comma>=0&&dot>=0){if(comma>dot)s=s.replace(/\./g,"").replace(",", ".");else s=s.replace(/,/g,"");}else if(comma>=0)s=s.replace(",", ".");const n=Number(s);return Number.isFinite(n)?n:null;}
function parseInvoice(text){const items=[];const unitMatch=String(text).match(/Unit\s*Price\s*=?\s*([0-9]+(?:[.,][0-9]+)?)/i);const unit=unitMatch?cleanNumber(unitMatch[1]):null;for(const part of String(text).split(/Order\s*#\s*\d+(?:\s*\([^)]+\))?\s*:/i)){const track=part.match(/Tracking\s*Number#?\s*:\s*([A-Za-z0-9\-]+)/i)?.[1]?.trim()||null;const weightMatch=part.match(/Weight\s*:\s*([0-9]+(?:[.,][0-9]+)?)\s*K?G?/i);const priceMatch=part.match(/Price\s*:\s*\$?\s*([0-9]+(?:[.,][0-9]+)?)/i);const deliveryMatch=part.match(/Delivery\s*:\s*\$?\s*([0-9]+(?:[.,][0-9]+)?)/i);const price=priceMatch?cleanNumber(priceMatch[1]):null;let weight=weightMatch?cleanNumber(weightMatch[1]):null;if(weight==null&&price!=null&&unit>0)weight=Math.round(price/unit*1000)/1000;if(track||price!=null||weight!=null)items.push({tracking_no:track,weight_kg:weight,customs_fee:price??0,unit_price:unit,delivery_fee:deliveryMatch?(cleanNumber(deliveryMatch[1])??0):0});}return items;}
router.post([...paths("importFromInvoice"),...paths("importCustomsFromInvoice")],asyncHandler(async(req,res)=>{const monthId=int(req.body?.month_id);const message=trim(req.body?.message);if(monthId<=0||!message)return err(res,400,"month_id and message are required");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user");const items=parseInvoice(message);if(!items.length)return err(res,400,"No invoice lines were parsed");let created=0;const skipped=[],notifications=[],out=[];for(const item of items){let effective=monthId,orderId=null,cartId=null,orderRef=null,cartRef=null,note=null;const tracking=item.tracking_no||null;if(tracking){const duplicate=await findDuplicateTracking(pool,uid(req),tracking);if(duplicate){skipped.push({tracking_no:tracking,reason:"duplicate tracking already exists",duplicate_id:Number(duplicate.id),month_id:Number(duplicate.month_id)});continue;}const ctx=await buildShipmentNoteContext(pool,uid(req),monthId,tracking);for(const n of ctx.notifications||[])notifications.push({tracking_no:tracking,message:String(n)});if(Number(ctx.resolved_month_id)>0)effective=Number(ctx.resolved_month_id);orderId=ctx.order_id;cartId=ctx.cart_id;orderRef=ctx.order_ref;cartRef=ctx.cart_ref;note=[cartRef,orderRef,...(ctx.note_parts||[])].map(trim).filter(Boolean).join(" | ")||null;}if(!(await ensureMonth(effective,uid(req)))||!(await customReferencesBelong(pool,uid(req),effective,orderId,cartId)))throw new HttpError(422,"Invoice item references an invalid user/month/order/cart",{ok:false,error:"Invoice item references an invalid user/month/order/cart"});const result=await execute(pool,`INSERT INTO customs (month_id,customs_fee,user_id,tracking_no,invoice_no,weight_kg,unit_price,delivery_fee,order_id,cart_id,order_ref,cart_ref,note,source_message) VALUES (?, ?, ?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,[effective,item.customs_fee,uid(req),tracking,item.weight_kg,item.unit_price,item.delivery_fee,orderId,cartId,orderRef,cartRef,note,message]);created++;out.push({id:Number(result.insertId),tracking_no:tracking,weight_kg:item.weight_kg,customs_fee:item.customs_fee,month_id:effective,order_ref:orderRef,cart_ref:cartRef});}res.json({success:true,created,items:out,skipped,notifications});}));

// Cargo package sorting/payroll endpoints.
router.get(paths("getCargoPackages",true),asyncHandler(async(req,res)=>{const monthId=int(req.query.month_id);if(monthId<=0)return err(res,400,"month_id is required","ok");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user","ok");const excluded=new Set(await pendingPayrollGroupKeys(pool,uid(req),monthId));const all=(await getCargoPackageGroups(pool,uid(req),monthId)).filter((r)=>!excluded.has(r.group_key));res.json({ok:true,pending:all.filter((r)=>!r.status),confirmed:all.filter((r)=>r.status),all});}));
router.get(paths("getPendingCargoPayrolls"),asyncHandler(async(req,res)=>{const monthId=int(req.query.month_id);if(monthId<=0)return err(res,400,"month_id is required","ok");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user","ok");const headers=await rows(pool,"SELECT id,per_unit_amount,sorted_count,total_payroll,note,summary_json,created_at FROM cargo_payroll_pending WHERE user_id=? AND month_id=? AND status='pending' ORDER BY id DESC",[uid(req),monthId]);const result=[];for(const h of headers){const packages=await rows(pool,"SELECT id,group_key,display_label,group_type,tracking_numbers_json,weight_kg,amount,order_refs_json FROM cargo_payroll_pending_packages WHERE pending_id=? ORDER BY id ASC",[h.id]);result.push({id:Number(h.id),per_unit_amount:Number(h.per_unit_amount||0),sorted_count:Number(h.sorted_count||0),total_payroll:Number(h.total_payroll||0),note:String(h.note||""),created_at:h.created_at,summary:typeof h.summary_json==="string"?jsonDecode(h.summary_json,null):h.summary_json,packages:packages.map((p)=>({id:Number(p.id),group_key:p.group_key,display_label:p.display_label,group_type:p.group_type||"single",tracking_numbers:typeof p.tracking_numbers_json==="string"?jsonDecode(p.tracking_numbers_json,[]):[],weight_kg:Number(p.weight_kg||0),amount:Number(p.amount||0),order_refs:typeof p.order_refs_json==="string"?jsonDecode(p.order_refs_json,[]):[]}))});}res.json({ok:true,pending_payrolls:result});}));
router.post(paths("getCargoPayrollPreview",true),asyncHandler(async(req,res)=>{const monthId=int(req.body?.month_id);const amount=number(req.body?.per_unit_amount);if(monthId<=0)return err(res,400,"month_id is required","ok");if(!finite(amount)||amount<0)return err(res,400,"per_unit_amount must be >= 0","ok");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user","ok");res.json({ok:true,preview:await buildPayrollBreakdown(pool,uid(req),monthId,amount,await pendingPayrollGroupKeys(pool,uid(req),monthId))});}));
router.get(paths("getCargoPayrollPreview",true),asyncHandler(async(req,res)=>{const monthId=int(req.query.month_id);const amount=number(req.query.per_unit_amount);if(monthId<=0)return err(res,400,"month_id is required","ok");if(!finite(amount)||amount<0)return err(res,400,"per_unit_amount must be >= 0","ok");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user","ok");res.json({ok:true,preview:await buildPayrollBreakdown(pool,uid(req),monthId,amount,await pendingPayrollGroupKeys(pool,uid(req),monthId))});}));
router.post(paths("confirmCargoPayroll"),asyncHandler(async(req,res)=>{const monthId=int(req.body?.month_id);const amount=number(req.body?.per_unit_amount);const note=trim(req.body?.note);if(monthId<=0)return err(res,400,"month_id is required","ok");if(!finite(amount)||amount<0)return err(res,400,"per_unit_amount must be >= 0","ok");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user","ok");const summary=await buildPayrollBreakdown(pool,uid(req),monthId,amount,await pendingPayrollGroupKeys(pool,uid(req),monthId));if(summary.sorted_count<=0)return err(res,400,"No sorted packages available for pending payment","ok");const autoNote=`Payroll pending | Sorted packages: ${summary.sorted_count} | Per unit: ${amount.toFixed(2)} | Total payroll: ${Number(summary.total_payroll||0).toFixed(2)}${note?` | ${note}`:""}`;const db=await pool.getConnection();try{await db.beginTransaction();const header=await execute(db,"INSERT INTO cargo_payroll_pending (month_id,user_id,per_unit_amount,sorted_count,total_payroll,status,note,summary_json) VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)",[monthId,uid(req),amount,summary.sorted_count,summary.total_payroll,autoNote,JSON.stringify(summary)]);for(const p of summary.packages){if(!p.group_key)continue;await execute(db,"INSERT INTO cargo_payroll_pending_packages (pending_id,group_key,display_label,group_type,tracking_numbers_json,weight_kg,amount,order_refs_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",[header.insertId,p.group_key,p.display_label,p.group_type,JSON.stringify(p.tracking_numbers||[]),p.weight_kg,p.amount,JSON.stringify(p.order_refs||[])]);}await db.commit();res.json({ok:true,message:"Payroll moved to pending payment. Accept is required to add to customs.",pending_id:Number(header.insertId),summary});}catch(e){try{await db.rollback();}catch(_){}throw e;}finally{db.release();}}));
router.post(paths("acceptPendingCargoPayroll"),asyncHandler(async(req,res)=>{const pendingId=int(req.body?.pending_id);if(pendingId<=0)return err(res,400,"pending_id is required","ok");const pending=await first(pool,"SELECT id,month_id,total_payroll,note,summary_json,status FROM cargo_payroll_pending WHERE id=? AND user_id=? LIMIT 1",[pendingId,uid(req)]);if(!pending)return err(res,404,"Pending payroll not found","ok");if(pending.status!=="pending")return err(res,400,"Pending payroll already accepted","ok");const finalNote=[trim(pending.note),trim(req.body?.note)].filter(Boolean).join(" | ");const db=await pool.getConnection();try{await db.beginTransaction();const custom=await execute(db,`INSERT INTO customs (month_id,customs_fee,user_id,tracking_no,invoice_no,weight_kg,unit_price,delivery_fee,order_id,cart_id,order_ref,cart_ref,note,description,source_message) VALUES (?, ?, ?, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, ?, 'payment', ?)`,[pending.month_id,pending.total_payroll,uid(req),finalNote,pending.summary_json]);await execute(db,"UPDATE cargo_payroll_pending SET status='accepted',accepted_at=NOW(),customs_id=? WHERE id=? AND user_id=? AND status='pending'",[custom.insertId,pendingId,uid(req)]);await db.commit();res.json({ok:true,message:"Pending payroll accepted and added to customs.",customs_id:Number(custom.insertId)});}catch(e){try{await db.rollback();}catch(_){}throw e;}finally{db.release();}}));
router.post(paths("setCargoPackageStatus"),asyncHandler(async(req,res)=>{const monthId=int(req.body?.month_id);const groupKey=trim(req.body?.group_key);const status=trim(req.body?.status);if(monthId<=0||!groupKey)return err(res,400,"month_id and group_key are required","ok");if(!["sorted","not_sorted"].includes(status))return err(res,400,"status must be sorted or not_sorted","ok");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user","ok");await execute(pool,`INSERT INTO cargo_package_sort_status (month_id,user_id,group_key,group_type,display_label,tracking_numbers_json,status,confirmed_at) VALUES (?, ?, ?, ?, ?, ?, ?, NOW()) ON DUPLICATE KEY UPDATE group_type=VALUES(group_type),display_label=VALUES(display_label),tracking_numbers_json=VALUES(tracking_numbers_json),status=VALUES(status),confirmed_at=NOW()`,[monthId,uid(req),groupKey,trim(req.body?.group_type)||"single",trim(req.body?.display_label),Array.isArray(req.body?.tracking_numbers)?JSON.stringify(req.body.tracking_numbers):null,status]);res.json({ok:true,group_key:groupKey,status});}));
router.get(paths("getDeliveredNotInCustoms"),asyncHandler(async(req,res)=>{const monthId=int(req.query.month_id);if(monthId<=0)return err(res,400,"month_id is required","ok");if(!(await ensureMonth(monthId,uid(req))))return err(res,403,"Invalid month for this user","ok");res.json({ok:true,packages:await getDeliveredNotInCustoms(pool,uid(req),monthId)});}));

module.exports = router;
