CREATE TABLE `delivery_losses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `month_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `status` enum('pending','confirmed') NOT NULL DEFAULT 'pending',
  `loss_type` varchar(64) NOT NULL,
  `amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `signed_diff` decimal(10,2) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `customer_name_snapshot` varchar(255) DEFAULT NULL,
  `order_id` int(11) DEFAULT NULL,
  `order_name_snapshot` varchar(255) DEFAULT NULL,
  `cart_id` int(11) DEFAULT NULL,
  `cart_order_number_snapshot` varchar(100) DEFAULT NULL,
  `ref_label` varchar(255) DEFAULT NULL,
  `source_key` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `confirmed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_delivery_losses_user_month_status` (`user_id`,`month_id`,`status`),
  KEY `idx_delivery_losses_customer` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
