const { rows, first } = require("./helpers");

const normTrack = (value) => String(value ?? "").trim().toUpperCase();
function parseTracks(value) {
  const parsed = typeof value === "string" ? (() => { try { return JSON.parse(value); } catch (_) { return []; } })() : value;
  if (!Array.isArray(parsed)) return [];
  const map = new Map(); for (const item of parsed) { const raw = String(item ?? "").trim(); if (raw) map.set(normTrack(raw), raw); } return [...map.values()];
}
function groupKey(type, tracks) { const normalized = [...new Set(tracks.map(normTrack).filter(Boolean))].sort(); return `${type}:${normalized.join(type === "split" ? "|" : "")}`; }

async function getCargoPackageGroups(db, userId, monthId) {
  const customs = await rows(db, `SELECT id,tracking_no,customs_fee,weight_kg,order_ref,cart_ref,note FROM customs WHERE user_id=? AND month_id=? AND tracking_no IS NOT NULL AND TRIM(tracking_no)<>'' ORDER BY id DESC`, [userId, monthId]);
  const carts = await rows(db, `SELECT oc.id AS cart_id,oc.cart_order_number,oc.shein_tracking_no,oc.shein_is_split_shipment,oc.shein_split_tracking_numbers_json,oc.is_joint_shipment,o.order_name FROM order_carts oc JOIN orders o ON o.id=oc.order_id AND o.user_id=oc.user_id WHERE oc.user_id=? AND o.month_id=? AND ((oc.shein_tracking_no IS NOT NULL AND TRIM(oc.shein_tracking_no)<>'') OR (oc.shein_split_tracking_numbers_json IS NOT NULL AND TRIM(oc.shein_split_tracking_numbers_json)<>''))`, [userId, monthId]);
  const refsByTrack = new Map(), splitKeyByTrack = new Map(), splitTracksByKey = new Map();
  const pushRef = (track, ref) => { if (!track) return; if (!refsByTrack.has(track)) refsByTrack.set(track, []); const refs = refsByTrack.get(track); if (!refs.includes(ref)) refs.push(ref); };
  for (const cart of carts) { const ref = `order ${String(cart.order_name ?? "").trim() || "-"} / cart ${String(cart.cart_order_number ?? "").trim() || "-"}`; const direct = normTrack(cart.shein_tracking_no); pushRef(direct, ref); const split = parseTracks(cart.shein_split_tracking_numbers_json); if (split.length >= 2) { const tracks = [...new Set(split.map(normTrack).filter(Boolean))].sort(); const key = `split:${tracks.join("|")}`; splitTracksByKey.set(key, tracks); for (const track of tracks) { splitKeyByTrack.set(track, key); pushRef(track, ref); } } }
  const statusRows = await rows(db, "SELECT group_key,status,confirmed_at FROM cargo_package_sort_status WHERE user_id=? AND month_id=?", [userId, monthId]); const statuses = new Map(statusRows.map((r) => [String(r.group_key), r])); const groups = new Map();
  for (const item of customs) { const track = normTrack(item.tracking_no); if (!track) continue; let type = "single", key = `single:${track}`, tracks = [track]; if (splitKeyByTrack.has(track)) { type = "split"; key = splitKeyByTrack.get(track); tracks = splitTracksByKey.get(key) || [track]; } else if ((refsByTrack.get(track) || []).length > 1) { type = "joint"; key = `joint:${track}`; }
    if (!groups.has(key)) { const status = statuses.get(key); groups.set(key, { group_key:key, group_type:type, display_label:"", tracking_numbers:tracks, order_cart_refs:[], entries_count:0, total_customs_fee:0, total_weight_kg:0, latest_custom_id:0, status:status?.status ?? null, confirmed_at:status?.confirmed_at ?? null, received:new Set() }); }
    const group = groups.get(key); group.entries_count++; group.total_customs_fee += Number(item.customs_fee || 0); group.total_weight_kg += Number(item.weight_kg || 0); group.latest_custom_id = Math.max(group.latest_custom_id, Number(item.id || 0)); group.received.add(track); const ownRef = `${trimValue(item.order_ref)}${trimValue(item.order_ref) && trimValue(item.cart_ref) ? " / " : ""}${trimValue(item.cart_ref)}`; if (ownRef.trim()) group.order_cart_refs.push(ownRef); }
  const out = [...groups.values()].map((group) => { for (const track of group.tracking_numbers) for (const ref of refsByTrack.get(track) || []) group.order_cart_refs.push(ref); group.order_cart_refs = [...new Set(group.order_cart_refs.filter((v) => String(v).trim()))]; group.display_label = group.group_type === "split" ? `Split package: ${group.tracking_numbers.join(" + ")}` : group.group_type === "joint" ? `Joint package: ${group.tracking_numbers.join(", ")}` : `Package: ${group.tracking_numbers.join(", ")}`; group.split_total_count = group.tracking_numbers.length; group.split_received_count = group.tracking_numbers.filter((t) => group.received.has(normTrack(t))).length; group.split_missing_tracking_numbers = group.tracking_numbers.filter((t) => !group.received.has(normTrack(t))); group.split_completed = group.group_type === "split" && group.split_received_count >= group.split_total_count ? 1 : 0; delete group.received; return group; });
  return out.sort((a, b) => b.latest_custom_id - a.latest_custom_id);
}
const trimValue = (value) => String(value ?? "").trim();

async function pendingPayrollGroupKeys(db, userId, monthId, pendingOnly = false) {
  const extra = pendingOnly ? " AND h.status='pending'" : ""; const result = await rows(db, `SELECT p.group_key FROM cargo_payroll_pending_packages p JOIN cargo_payroll_pending h ON h.id=p.pending_id WHERE h.user_id=? AND h.month_id=?${extra}`, [userId, monthId]); return [...new Set(result.map((r) => trimValue(r.group_key)).filter(Boolean))];
}

async function buildPayrollBreakdown(db, userId, monthId, perUnitAmount, excludeKeys = []) {
  const excluded = new Set(excludeKeys); const groups = (await getCargoPackageGroups(db, userId, monthId)).filter((g) => g.status === "sorted" && !excluded.has(g.group_key)); const packages = []; const orderTotals = new Map(); let total = 0;
  for (const group of groups) { const weight = Number(group.total_weight_kg || 0); const free = weight < 10; const amount = free ? 0 : perUnitAmount; total += amount; const orderKeys = []; for (const ref of group.order_cart_refs || []) { const match = String(ref).match(/order\s+([^/]+)\s*\/\s*cart/i); if (match?.[1]?.trim()) orderKeys.push(match[1].trim()); } const orders = [...new Set(orderKeys)]; if (!orders.length) orders.push("Unknown"); const share = amount / orders.length; for (const order of orders) orderTotals.set(order, (orderTotals.get(order) || 0) + share); packages.push({ group_key:group.group_key, display_label:group.display_label, group_type:group.group_type, tracking_numbers:group.tracking_numbers, weight_kg:weight, is_free_under_10kg:free ? 1 : 0, amount, order_refs:group.order_cart_refs || [], orders }); }
  return { per_unit_amount:perUnitAmount, sorted_count:groups.length, packages, orders:[...orderTotals.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([order_name,amount])=>({order_name,amount})), orders_count:orderTotals.size, total_payroll:total };
}

async function getDeliveredNotInCustoms(db, userId, monthId) {
  const customs = await rows(db, "SELECT tracking_no FROM customs WHERE user_id=? AND month_id=? AND tracking_no IS NOT NULL AND TRIM(tracking_no)<>''", [userId, monthId]); const customTracks = new Set(customs.map((r) => normTrack(r.tracking_no)).filter(Boolean)); const carts = await rows(db, `SELECT oc.id AS cart_id,oc.order_id,oc.cart_order_number,oc.shein_tracking_no,oc.shein_split_tracking_numbers_json,oc.shein_delivered,o.order_name FROM order_carts oc JOIN orders o ON o.id=oc.order_id AND o.user_id=oc.user_id WHERE oc.user_id=? AND o.month_id=? AND COALESCE(oc.shein_delivered,0)=1 AND ((oc.shein_tracking_no IS NOT NULL AND TRIM(oc.shein_tracking_no)<>'') OR (oc.shein_split_tracking_numbers_json IS NOT NULL AND TRIM(oc.shein_split_tracking_numbers_json)<>'')) ORDER BY oc.id DESC`, [userId, monthId]); const refs=new Map(), splitByTrack=new Map(), splitByKey=new Map(), all=new Set(); const add=(k,v)=>{if(!refs.has(k))refs.set(k,[]);const values=refs.get(k);if(!values.includes(v))values.push(v);}; for(const c of carts){const ref=`order ${trimValue(c.order_name)||"-"} / cart ${trimValue(c.cart_order_number)||"-"}`; const direct=normTrack(c.shein_tracking_no);if(direct){add(direct,ref);all.add(direct);} const split=parseTracks(c.shein_split_tracking_numbers_json);if(split.length>=2){const tracks=[...new Set(split.map(normTrack).filter(Boolean))].sort();const key=`split:${tracks.join("|")}`;splitByKey.set(key,tracks);for(const t of tracks){splitByTrack.set(t,key);add(t,ref);all.add(t);}}} const groups=new Map(); for(const track of all){let type="single",key=`single:${track}`,tracks=[track];if(splitByTrack.has(track)){type="split";key=splitByTrack.get(track);tracks=splitByKey.get(key);}else if((refs.get(track)||[]).length>1){type="joint";key=`joint:${track}`;}if(!groups.has(key))groups.set(key,{group_key:key,group_type:type,tracking_numbers:tracks,order_cart_refs:[]});for(const t of tracks)for(const ref of refs.get(t)||[])groups.get(key).order_cart_refs.push(ref);} return [...groups.values()].map(g=>{g.order_cart_refs=[...new Set(g.order_cart_refs)];const added=g.tracking_numbers.filter(t=>customTracks.has(normTrack(t))),missing=g.tracking_numbers.filter(t=>!customTracks.has(normTrack(t)));return {...g,display_label:g.group_type==="split"?`Split package: ${g.tracking_numbers.join(" + ")}`:g.group_type==="joint"?`Joint package: ${g.tracking_numbers.join(", ")}`:`Package: ${g.tracking_numbers.join(", ")}`,added_to_customs_tracking_numbers:added,missing_from_customs_tracking_numbers:missing,is_fully_missing:added.length===0?1:0};}).filter(g=>g.missing_from_customs_tracking_numbers.length).sort((a,b)=>b.is_fully_missing-a.is_fully_missing); }

module.exports = { normTrack, parseTracks, getCargoPackageGroups, pendingPayrollGroupKeys, buildPayrollBreakdown, getDeliveredNotInCustoms };
