const { first, rows, execute, placeholders, jsonDecode, trim } = require("./helpers");

async function findDuplicateTracking(db, userId, trackingNo) {
  const tracking = trim(trackingNo); if (!tracking) return null;
  return first(db, "SELECT id,month_id,tracking_no FROM customs WHERE user_id=? AND tracking_no IS NOT NULL AND UPPER(TRIM(tracking_no))=UPPER(TRIM(?)) ORDER BY id DESC LIMIT 1", [userId, tracking]);
}

function cleanSplitNote(note) {
  return String(note || "").split(/\s*\|\s*/).map((v) => v.trim()).filter((v) => v && !/waiting for next split package/i.test(v) && !/split shipment pending - waiting for next package/i.test(v) && !/^split received:/i.test(v) && !/^split received from package\(s\):/i.test(v)).filter((v, i, a) => a.indexOf(v) === i).join(" | ");
}

async function buildShipmentNoteContext(db, userId, monthId, trackingNo, applySideEffects = true) {
  const tracking = trim(trackingNo); const blank = { order_id:null, cart_id:null, order_ref:null, cart_ref:null, note_parts:[], notifications:[], resolved_month_id:monthId, split_conflict:0 }; if (!tracking) return blank;
  let cartRows = await rows(db, `SELECT oc.id AS cart_id,oc.order_id,oc.cart_order_number,oc.shein_tracking_no,oc.shein_is_split_shipment,oc.shein_split_tracking_numbers_json,o.order_name FROM order_carts oc JOIN orders o ON o.id=oc.order_id AND o.user_id=oc.user_id WHERE oc.user_id=? AND UPPER(TRIM(oc.shein_tracking_no))=UPPER(TRIM(?)) ORDER BY oc.id ASC`, [userId, tracking]);
  if (!cartRows.length) { const likeQuoted = `%"${tracking}"%`; cartRows = await rows(db, `SELECT oc.id AS cart_id,oc.order_id,oc.cart_order_number,oc.shein_tracking_no,oc.shein_is_split_shipment,oc.shein_split_tracking_numbers_json,o.order_name FROM order_carts oc JOIN orders o ON o.id=oc.order_id AND o.user_id=oc.user_id WHERE oc.user_id=? AND (oc.shein_split_tracking_numbers_json LIKE ? OR oc.shein_split_tracking_numbers_json LIKE ?) ORDER BY oc.id ASC`, [userId, likeQuoted, `%${tracking}%`]); }
  if (!cartRows.length) return blank;
  const firstCart = cartRows[0]; const orderId = Number(firstCart.order_id); const cartId = Number(firstCart.cart_id); const orderRef = `order ${trim(firstCart.order_name) || orderId}`; const cartRef = `cart ${trim(firstCart.cart_order_number)}`; const noteParts = []; const notifications=[];
  if (cartRows.length > 1) { const refs=[...new Set(cartRows.map((r)=>`order ${trim(r.order_name)||r.order_id} / cart ${trim(r.cart_order_number)}`))]; if(refs.length)noteParts.push(`Joint shipment with: ${refs.join(" ; ")}`); }
  const splitSets = new Set(), peers = new Map(); for(const row of cartRows){const parsed=jsonDecode(row.shein_split_tracking_numbers_json,[]);if(!Array.isArray(parsed))continue;const set=[...new Set([...parsed.map((v)=>String(v).trim().toUpperCase()),tracking.toUpperCase()].filter(Boolean))].sort();if(set.length)splitSets.add(set.join("|"));for(const value of parsed){const peer=trim(value);if(peer&&peer.toUpperCase()!==tracking.toUpperCase())peers.set(peer.toUpperCase(),peer);}}
  if(splitSets.size>1){notifications.push("Warning: inconsistent split definitions detected for this tracking in order carts.");}
  const peerTracks=[...peers.values()]; let resolvedMonthId=monthId;
  if(peerTracks.length){ const peerRows=await rows(db,`SELECT month_id,tracking_no FROM customs WHERE user_id=? AND tracking_no IS NOT NULL AND tracking_no IN (${placeholders(peerTracks)}) ORDER BY id DESC`,[userId,...peerTracks]); const months=[...new Set(peerRows.map((r)=>Number(r.month_id)).filter((v)=>v>0))]; if(months.length===1&&months[0]!==monthId){resolvedMonthId=months[0];notifications.push(`Split sibling already exists in month ${months[0]}; item will be added to that month.`);}else if(months.length>1)notifications.push(`Warning: split siblings exist across multiple months (${months.join(", ")}). Kept selected month.`);
    const pending=await rows(db,`SELECT id,tracking_no,order_ref,cart_ref,note FROM customs WHERE user_id=? AND month_id=? AND tracking_no IS NOT NULL AND tracking_no IN (${placeholders(peerTracks)}) AND (COALESCE(note,'') LIKE '%waiting for next split package%' OR COALESCE(note,'') LIKE '%Split shipment pending%') ORDER BY id DESC`,[userId,resolvedMonthId,...peerTracks]);
    if(pending.length){const seenRefs=[...new Set(pending.map((r)=>{const bits=[trim(r.tracking_no),trim(r.order_ref),trim(r.cart_ref)].filter(Boolean);return bits.join(" / ");}))];if(applySideEffects){for(const row of pending){const updated=[cleanSplitNote(row.note),`Split received: ${tracking}`].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(" | ");await execute(db,"UPDATE customs SET note=? WHERE id=? AND user_id=?",[updated,row.id,userId]);}}noteParts.push(`Split received from package(s): ${seenRefs.join(", ")}`);}else noteParts.push(`Split shipment pending - waiting for next package(s): ${peerTracks.join(", ")}`);
  }
  return { order_id:orderId, cart_id:cartId, order_ref:orderRef, cart_ref:cartRef, note_parts:noteParts, notifications, resolved_month_id:resolvedMonthId, split_conflict:splitSets.size>1?1:0 };
}

async function refreshSplitNotesForTracking(db, userId, monthId, trackingNo) {
  const tracking=trim(trackingNo).toUpperCase();if(!tracking)return;const related=await rows(db,`SELECT shein_split_tracking_numbers_json FROM order_carts WHERE user_id=? AND (UPPER(TRIM(shein_tracking_no))=? OR shein_split_tracking_numbers_json LIKE ? OR shein_split_tracking_numbers_json LIKE ?)`,[userId,tracking,`%"${tracking}"%`,`%${tracking}%`]);const tracks=new Map([[tracking,tracking]]);for(const row of related)for(const t of jsonDecode(row.shein_split_tracking_numbers_json,[])||[]){const value=trim(t).toUpperCase();if(value)tracks.set(value,value);}const trackList=[...tracks.values()];const monthRows=monthId>0?[{month_id:monthId}]:[];const otherMonths=await rows(db,`SELECT DISTINCT month_id FROM customs WHERE user_id=? AND tracking_no IN (${placeholders(trackList)})`,[userId,...trackList]);const months=[...new Set([...monthRows.map((r)=>Number(r.month_id)),...otherMonths.map((r)=>Number(r.month_id))].filter((v)=>v>0))];for(const target of months){const customs=await rows(db,`SELECT id,tracking_no,note FROM customs WHERE user_id=? AND month_id=? AND tracking_no IN (${placeholders(trackList)})`,[userId,target,...trackList]);for(const row of customs){const base=cleanSplitNote(row.note);const ctx=await buildShipmentNoteContext(db,userId,target,row.tracking_no,false);const parts=[base,...(ctx.note_parts||[])].map(trim).filter(Boolean);await execute(db,"UPDATE customs SET note=? WHERE id=? AND user_id=?",[[...new Set(parts)].join(" | "),row.id,userId]);}} }

module.exports = { findDuplicateTracking, buildShipmentNoteContext, refreshSplitNotesForTracking };
